### ISSUE TITLE
能否分离qqbot与ykkz

### ISSUE THREAD

**Issue by fffzzl** [123summertime/ykkz#1]
反向ws的配置哪里可调（

**Comment by 123summertime** [comment]
在config.yml最下面可以调反向ws的端口(go-cq的)
在ykkz/.env.prod下的PORT调反向ws的端口(nonebot的)

分离肯定是能分离的，当初本来打算作为一个插件发布的，但是配置过程过于麻烦，最后还是打包了整个机器人项目。

**Comment by fffzzl** [comment]
晚上忙活了半天，又看来一遍nonebot找到了（ 不过运行起来还是有问题，也可能是只配置了vitsPath的问题，我看后面的pth configpath都与语言有关，不需要就没配置

```
C:\Users\fanze\Documents\ykkz-main\ykkz>nb run
10-07 23:04:07 [SUCCESS] nonebot | NoneBot is initializing...
10-07 23:04:07 [INFO] nonebot | Current Env: prod
10-07 23:04:07 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('192.168.31.238'), 'port': 14514, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'prod'}
10-07 23:04:07 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-07 23:04:07 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-07 23:04:08 [ERROR] nonebot | Failed to import "ykkz_core"
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\fanze\Documents\ykkz-main\ykkz\src\plugins\ykkz_core\__init__.py", line 6, in <module>
    from .utils import Utils, Scheduled, Voice
  File "C:\Users\fanze\Documents\ykkz-main\ykkz\src\plugins\ykkz_core\utils.py", line 23, in <module>
    Multimedia = json.load(r)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 46 column 18 (char 759)
10-07 23:04:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-07 23:04:08 [SUCCESS] nonebot | Running NoneBot...
10-07 23:04:08 [DEBUG] nonebot | Loaded adapters: OneBot V11
10-07 23:04:08 [WARNING] uvicorn | You must pass the application as an import string to enable 'reload' or 'workers'.

```

**Comment by fffzzl** [comment]
或者打包成ws或者http的包，模型默认相对路径，模型一丢就能独立运行

**Comment by 123summertime** [comment]
Multi.json JSON解析错误？看看Multi.json第46行是不是有什么问题

**Comment by fffzzl** [comment]
是  "vitsPath": "C:\Users\fanze\Documents\ykkz-main\ykkz\vits",
删掉后就不报错了

  _"timePlusOrMinus": 3,
  "ScheduledGroup": 667453323 ,
  "voiceEnable": false,
  "voiceSpeed": "-5%",
  "voiceVolume": "+5%",
  "vitsEnable": false,
  "vitsPath": "C:\Users\fanze\Documents\ykkz-main\ykkz\vits",
  "pthPath": "",
  "configPath": "",
  "speaker": "",
  "trans": 0
}_

但运行后就结束
_C:\Users\fanze\Documents\ykkz-main\ykkz>nb run
10-07 23:16:43 [SUCCESS] nonebot | NoneBot is initializing...
10-07 23:16:43 [INFO] nonebot | Current Env: prod
10-07 23:16:43 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('192.168.31.238'), 'port': 14514, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'prod'}
10-07 23:16:43 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-07 23:16:44 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-07 23:16:44 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
00:01
10-07 23:16:44 [SUCCESS] nonebot | Succeeded to load plugin "ykkz_core" from "src.plugins.ykkz_core"
10-07 23:16:44 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-07 23:16:44 [SUCCESS] nonebot | Running NoneBot...
10-07 23:16:45 [DEBUG] nonebot | Loaded adapters: OneBot V11
10-07 23:16:45 [WARNING] uvicorn | You must pass the application as an import string to enable 'reload' or 'workers'._

**Comment by 123summertime** [comment]
转义字符的问题
![image](https://github.com/123summertime/ykkz/assets/73610948/0a0e4b58-13ef-493c-8da2-b0b0185e61ba)
两个\\才代表一个\

**Comment by 123summertime** [comment]
nb run --reload试一下

**Comment by fffzzl** [comment]
不是--reload的问题，我重置环境就好了，还有刚才用mac pip3 安装requirements.txt时 有个pywin32的依赖只提供给windows，去掉后还有两个版本报错，忽略后也可以运行bot.py（上面不重要，下面是问题）

mirai对接反向ws 时403

_2023-10-08 18:08:14 W/stderr: Exception in thread "DefaultDispatcher-worker-9" java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
2023-10-08 18:08:14 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
2023-10-08 18:08:14 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
2023-10-08 18:08:14 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2023-10-08 18:08:14 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-10-08 18:08:14 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-10-08 18:08:14 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2023-10-08 18:08:14 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@68892afb, Dispatchers.Default]_

在nbbot上为

_10-08 17:53:33 [INFO] uvicorn | Uvicorn running on http://192.168.31.238:14514 (Press CTRL+C to quit)
10-08 17:53:33 [INFO] uvicorn | Started reloader process [21532] using WatchFiles
10-08 17:53:34 [SUCCESS] nonebot | NoneBot is initializing...
10-08 17:53:34 [INFO] nonebot | Current Env: prod
10-08 17:53:34 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('192.168.31.238'), 'port': 14514, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'prod', 'fastapi_reload': True}
10-08 17:53:34 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-08 17:53:34 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
00:01
10-08 17:53:35 [SUCCESS] nonebot | Succeeded to load plugin "ykkz_core" from "src.plugins.ykkz_core"
10-08 17:53:35 [INFO] uvicorn | Started server process [2480]
10-08 17:53:35 [INFO] uvicorn | Waiting for application startup.
10-08 17:53:35 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-08 17:53:35 [INFO] uvicorn | Application startup complete.
10-08 18:08:13 [WARNING] nonebot | OneBot V11 | Missing X-Self-ID Header
10-08 18:08:13 [INFO] uvicorn | ('192.168.31.105', 55537) - "WebSocket /onebot/v11/ws/" 403
10-08 18:08:13 [INFO] websockets | connection failed (403 Forbidden)
10-08 18:08:13 [INFO] websockets | connection closed_

api-http配置
```
## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws
  - reverse-ws
## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: INxxxxxxxx
。忽略。。
  reverse-ws:
    ## 远端 websocket server 地址配置
    destinations:
      ## 请远端 server host
    - host: 192.168.31.238
      ## 远端 server 端口
      port: 14514
      ## 请求路径
      path: /onebot/v11/ws/
      ## 协议，[ws, wss]
      protocol: ws
      ## 请求方式，通常为 GET
      method: GET
      ## 重试连接的间隔（以毫秒计)
      reconnectInterval: 10000
```
跟着cqhttp配的
配置参考：https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/ReverseWebsocketAdapter.md

**Comment by fffzzl** [comment]
> 转义字符的问题 ![image](https://user-images.githubusercontent.com/73610948/273394265-0a0e4b58-13ef-493c-8da2-b0b0185e61ba.png) 两个\才代表一个\

好像是这样子的

**Comment by 123summertime** [comment]
vits的requirements.txt是分win和linux的，我认为用户大部分会用win，所以就没有把linux的那部分放上去，在readme中没有写清楚给你造成了麻烦感到十分抱歉。可以去ykkz/vits下安装vits部分的requirements，这个项目下的requirements不能安装的部分就过吧。

尝试在extraHeaders里加一个X-Self-ID的请求头，内容是QQ号。~我猜的~
https://github.com/botuniverse/onebot-11/blob/master/communication/ws-reverse.md#%E8%BF%9E%E6%8E%A5%E8%AF%B7%E6%B1%82

**Comment by fffzzl** [comment]
好消息改请求头和内容后连上了
```
10-08 23:30:10 [INFO] uvicorn | Uvicorn running on http://192.168.31.238:14514 (Press CTRL+C to quit)
10-08 23:30:10 [INFO] uvicorn | Started reloader process [11456] using WatchFiles
10-08 23:30:10 [SUCCESS] nonebot | NoneBot is initializing...
10-08 23:30:10 [INFO] nonebot | Current Env: prod
10-08 23:30:10 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('192.168.31.238'), 'port': 14514, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'prod', 'fastapi_reload': True}
10-08 23:30:10 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
10-08 23:30:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
00:01
10-08 23:30:11 [SUCCESS] nonebot | Succeeded to load plugin "ykkz_core" from "src.plugins.ykkz_core"
10-08 23:30:12 [INFO] uvicorn | Started server process [5688]
10-08 23:30:12 [INFO] uvicorn | Waiting for application startup.
10-08 23:30:12 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-08 23:30:12 [INFO] uvicorn | Application startup complete.
10-08 23:31:39 [INFO] uvicorn | ('192.168.31.105', 57037) - "WebSocket /onebot/v11/ws/" [accepted]
10-08 23:31:39 [INFO] nonebot | OneBot V11 | Bot 1220481280 connected
10-08 23:31:39 [INFO] websockets | connection open
```
坏消息是聊天内容没有传回nbbot

api http 配置
```
  reverse-ws:
    ## 远端 websocket server 地址配置
    destinations:
      ## 请远端 server host
    - host: 192.168.31.238
      ## 远端 server 端口
      port: 14514
      ## 请求路径
      path: /onebot/v11/ws/
      ## 协议，[ws, wss]
      protocol: ws
      ## 请求方式，通常为 GET
      method: GET
      ## 额外请求头，该连接有效
      extraHeaders:
      X-Self-ID: 1220481280
      ## 重试连接的间隔（以毫秒计)
      reconnectInterval: 10000

```

```
2023-10-08 23:31:38 W/mirai-api-http: USING INITIAL KEY, please edit the key
2023-10-08 23:31:38 I/Mirai HTTP API: ********************************************************
2023-10-08 23:31:38 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-10-08 23:31:38 I/MahKtorAdapter[http]: Application started in 0.276 seconds.
2023-10-08 23:31:38 I/MahKtorAdapter[http]: Responding at http://0.0.0.0:8001
2023-10-08 23:31:38 I/http adapter: >>> [http adapter] is listening at http://0.0.0.0:8001
2023-10-08 23:31:38 I/MahKtorAdapter[ws]: Autoreload is disabled because the development mode is off.
2023-10-08 23:31:38 I/MahKtorAdapter[ws]: Application started in 0.018 seconds.
2023-10-08 23:31:38 I/MahKtorAdapter[ws]: Responding at http://0.0.0.0:8002
2023-10-08 23:31:38 I/ws adapter: >>> [ws adapter] is listening at ws://0.0.0.0:8002
2023-10-08 23:31:38 I/reverse-ws adapter: >>> [reverse-ws adapter] is running
2023-10-08 23:31:38 I/Mirai HTTP API: Http api server is running with verifyKey: INxxxxxxxxxxx
2023-10-08 23:31:38 I/Mirai HTTP API: adaptors: [http,ws,reverse-ws]
2023-10-08 23:31:38 I/Mirai HTTP API: ********************************************************

```
后面mirai聊天记录跟之前没有变化

**Comment by 123summertime** [comment]
已更新readme，新增了将这个项目作为nonebot插件使用的方法
