### ISSUE TITLE
表情包发送路径问题

### ISSUE THREAD

**Issue by fffzzl** [123summertime/ykkz#2]
mirai使用onebot http插件连接上了局域网的本机，在发送表情包时出现错误，看了一下居然是直接调用文件路径 :0
具体为ykkz主机连接局域网服务器，发送图片时
```
10-09 17:16:19 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
10-09 17:16:33 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
10-09 17:16:33 [INFO] nonebot | Matcher(type='message', module=src.plugins.ykkz_core) running complete
10-09 17:16:33 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.ykkz_core) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\fanze\Documents\ykkz-main\ykkz\src\plugins\ykkz_core\__init__.py", line 143, in chatCore
    MessageID.append(await chat_Core.send(Message(f"[CQ:image,file=file:///{pic}]")))
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher\matcher.py", line 467, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 221, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 143, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\fanze\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=103, data=None, echo='19')
10-09 17:16:33 [DEBUG] nonebot | Stop event propagation
10-09 17:16:33 [DEBUG] nonebot | Checking for matchers completed
```
而局域网服务器的mirai 与ykkz并不是一台服务器没有那个文件，所以file:/boom！。也许可以ws传输表情包解决异地部署问题（坑快踩完了）
```
2023-10-09 17:16:33 E/OneBot: java.net.URISyntaxException: Illegal character in path at index 80: file:/C:/Users/fanze/Documents/ykkz-main/ykkz/src/plugins/ykkz_core/pics/other/a (15).jpg
java.net.URISyntaxException: Illegal character in path at index 80: file:/C:/Users/fanze/Documents/ykkz-main/ykkz/src/plugins/ykkz_core/pics/other/a (15).jpg
        at java.base/java.net.URI$Parser.fail(Unknown Source)
        at java.base/java.net.URI$Parser.checkChars(Unknown Source)
        at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.base/java.net.URI$Parser.parse(Unknown Source)
        at java.base/java.net.URI.<init>(Unknown Source)
        at java.base/java.net.URL.toURI(Unknown Source)
        at onebot-mirai-0.3.4-all.jar//com.github.yyuueexxiinngg.onebot.util.CQMessgeParserKt$tryResolveMedia$2.invokeSuspend(CQMessgeParser.kt:368)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by 123summertime** [comment]
等我晚上改成用base64传

**Comment by 123summertime** [comment]
已修复。修改了utils.py和__init__.py。
